# Generated by Django 4.2.13 on 2024-06-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("author_name", models.CharField(max_length=32, verbose_name="作者名")),
            ],
            options={
                "db_table": "author",
            },
        ),
        migrations.CreateModel(
            name="Manage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_number", models.CharField(max_length=32, verbose_name="账号")),
                ("user_password", models.CharField(max_length=32, verbose_name="密码")),
                ("user_name", models.CharField(max_length=32, verbose_name="名字")),
            ],
            options={
                "db_table": "manage",
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publisher_name",
                    models.CharField(max_length=32, verbose_name="出版社名称"),
                ),
                (
                    "publisher_address",
                    models.CharField(max_length=32, verbose_name="出版社地址"),
                ),
            ],
            options={
                "db_table": "publisher",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="书名")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "inventory",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="库存"
                    ),
                ),
                (
                    "sale_num",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="销量"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.author",
                        verbose_name="作者",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.publisher",
                        verbose_name="出版社",
                    ),
                ),
            ],
            options={
                "db_table": "book",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.publisher",
                verbose_name="出版社",
            ),
        ),
    ]
